import{a as r,l as k}from"./assets/lightbox-DTajK_My.js";/* empty css                      */import{i as c}from"./assets/vendor-D94OL8Qp.js";const O=document.getElementById("search-button"),l=document.querySelector(".gallery"),f=document.querySelector("#search-bar");let s=0,i=!0,u="",a=1;const q=document.querySelector(".gallery"),I={root:null,rootMargin:"0px",threshold:.5},d=new IntersectionObserver(C,I);O.addEventListener("click",function(e){e.preventDefault(),h(),i=!0});f.addEventListener("keydown",function(e){e.key==="Enter"&&(e.preventDefault(),h()),i=!0});async function h(){const e=f.value.trim();if(r.setQuery(e),e===""){p("Будь ласка, заповніть поле пошуку");return}if(e===u){p("Будь ласка, змініть або введіть новий запит до поля пошуку.");return}l.innerHTML="",r.resetPage(),u=e,s=0,a=1,await g()}async function g(){try{const e=await r.fetchGallery(),{hits:t,totalHits:o}=e;if(!t.length){m("Вибачте, немає зображень, які відповідають вашому запиту. Будь ласка, спробуйте ще раз.");return}i&&s<o&&(H(`Ура! Ми знайшли ${o} зображень !!!`),i=!1),$(t),s+=t.length;const n=l.lastElementChild;n&&d.observe(n),s>=o&&(d.disconnect(),T("Ви досягли кінця результатів пошуку."))}catch(e){console.error("Помилка отримання галереї:",e),m("Під час отримання галереї сталася помилка.")}}async function L(e){return(await axios.get("https://api.example.com/images",{params:{q:e,page:a,per_page:20}})).data}async function y(){const e=document.querySelector("#search-bar").value,t=await L(e),o=t.hits.map(n=>`<div class="gallery-item"><img src="${n.webformatURL}" alt="${n.tags}"></div>`).join("");q.insertAdjacentHTML("beforeend",o),a*20>=t.totalHits&&(document.querySelector("#load-more").hidden=!0,alert("Вибачте, але ви досягли кінця результатів пошуку.")),w(),a++}window.addEventListener("scroll",()=>{window.innerHeight+window.scrollY>=document.documentElement.scrollHeight&&y()});document.querySelector("#load-more").addEventListener("click",y);function $(e){const t=e.map(({webformatURL:o,largeImageURL:n,tags:b,likes:v,views:E,downloads:S})=>`
      <div class="photo-card">
        <a href="${n}">
          <img class="photo-img" src="${o}" alt="${b}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span class="info__span">${v}</span></p>
          <p class="info-item"><b>Views</b><span class="info__span">${E}</span></p>
          <p class="info-item"><b>Downloads</b><span class="info__span">${S}</span></p>
        </div>
      </div>`).join("");l.insertAdjacentHTML("beforeend",t),k.refresh(),w()}function C(e,t){e.forEach(o=>{o.isIntersecting&&(r.incrementPage(),g())})}function w(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function p(e){c.warning({title:"Warning",message:e,position:"topRight",color:"yellow",timeout:4e3,closeOnEscape:!0,closeOnClick:!0})}function m(e){c.error({title:"Error",message:e,position:"topRight",color:"red",timeout:3e3,closeOnEscape:!0,closeOnClick:!0})}function H(e){c.success({title:"Success",message:e,position:"topRight",color:"green",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}function T(e){c.info({title:"Info",message:e,position:"topRight",color:"blue",timeout:3e3,closeOnEscape:!0,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers2.js.map
